// AUTO-GENERATED by generate-boards.mjs from ../allora-fpga/src/data.
// Do not edit by hand — re-run `node generate-boards.mjs` instead.
window.ALLORA_BOARDS_FULL = [
  {
    "name": "ButterStick",
    "family": "ECP5",
    "fpga": "LFE5UM5G-25F",
    "pins": 22,
    "clock": "30 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "24,288 LUT4",
    "mem": "1,008 Kb BRAM",
    "best": "High-speed ECP5 (5G) projects with DDR3."
  },
  {
    "name": "Cam Link 4K",
    "family": "ECP5",
    "fpga": "LFE5U-25F",
    "pins": 1,
    "clock": "27 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "24,288 LUT4",
    "mem": "1,008 Kb BRAM",
    "best": "Open-source ECP5 development on the full Yosys + nextpnr flow."
  },
  {
    "name": "Colorlight i5",
    "family": "ECP5",
    "fpga": "LFE5U-25F",
    "pins": 16,
    "clock": "25 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "24,288 LUT4",
    "mem": "1,008 Kb BRAM",
    "best": "Low-cost ECP5 deployments and LED-panel driving."
  },
  {
    "name": "ECPIX-5",
    "family": "ECP5",
    "fpga": "LFE5UM5G-45F",
    "pins": 18,
    "clock": "100 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "43,848 LUT4",
    "mem": "1,944 Kb BRAM",
    "best": "Networking and PCIe-class ECP5 development."
  },
  {
    "name": "Fomu PVT",
    "family": "iCE40",
    "fpga": "ICE40-UP5K",
    "pins": 16,
    "clock": "48 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "5,280 LUT4",
    "mem": "120 Kb BRAM + 1 Mb SPRAM",
    "best": "Designs that live entirely inside a USB port."
  },
  {
    "name": "Fpc Iii",
    "family": "ECP5",
    "fpga": "LFE5U-85F",
    "pins": 37,
    "clock": "25 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "83,640 LUT4",
    "mem": "3,744 Kb BRAM",
    "best": "Open-source ECP5 development on the full Yosys + nextpnr flow."
  },
  {
    "name": "Hackaday Hadbadge",
    "family": "ECP5",
    "fpga": "LFE5U-45F",
    "pins": 28,
    "clock": "8 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "43,848 LUT4",
    "mem": "1,944 Kb BRAM",
    "best": "Conference-badge demos and learning projects."
  },
  {
    "name": "iCE-V Wireless",
    "family": "iCE40",
    "fpga": "ICE40-UP5K",
    "pins": 13,
    "clock": "12 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "5,280 LUT4",
    "mem": "120 Kb BRAM + 1 Mb SPRAM",
    "best": "Wireless, ESP32-paired iCE40 edge projects."
  },
  {
    "name": "iCEBreaker",
    "family": "iCE40",
    "fpga": "iCE40UP5K",
    "pins": 24,
    "clock": "12 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "5,280 LUT4",
    "mem": "120 Kb BRAM + 1 Mb SPRAM",
    "best": "Learning open-source FPGA flows and RISC-V on PMODs."
  },
  {
    "name": "iCEBreaker Bitsy",
    "family": "iCE40",
    "fpga": "ICE40-UP5K",
    "pins": 10,
    "clock": "12 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "5,280 LUT4",
    "mem": "120 Kb BRAM + 1 Mb SPRAM",
    "best": "Open-source iCE40 development on the full Yosys + nextpnr flow."
  },
  {
    "name": "iCEpi Zero",
    "family": "ECP5",
    "fpga": "LFE5U-25F",
    "pins": 14,
    "clock": "50 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "24,288 LUT4",
    "mem": "1,008 Kb BRAM",
    "best": "Open-source ECP5 development on the full Yosys + nextpnr flow."
  },
  {
    "name": "iCESugar Pro",
    "family": "ECP5",
    "fpga": "LFE5UM5G-25F",
    "pins": 15,
    "clock": "25 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "24,288 LUT4",
    "mem": "1,008 Kb BRAM",
    "best": "ECP5 prototyping with onboard debug and PMODs."
  },
  {
    "name": "iCESugar v1.5",
    "family": "iCE40",
    "fpga": "ICE40-UP5K",
    "pins": 40,
    "clock": "12 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "5,280 LUT4",
    "mem": "120 Kb BRAM + 1 Mb SPRAM",
    "best": "Compact iCE40 dev with an onboard debugger and PMODs."
  },
  {
    "name": "Lattice ECP5 EVN",
    "family": "ECP5",
    "fpga": "LFE5UM5G-85F",
    "pins": 15,
    "clock": "12 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "83,640 LUT4",
    "mem": "3,744 Kb BRAM",
    "best": "Official Lattice ECP5 evaluation and bring-up."
  },
  {
    "name": "Lattice ECP5 Vip",
    "family": "ECP5",
    "fpga": "LFE5UM-85F",
    "pins": 23,
    "clock": "27 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "83,640 LUT4",
    "mem": "3,744 Kb BRAM",
    "best": "Open-source ECP5 development on the full Yosys + nextpnr flow."
  },
  {
    "name": "Lattice iCE40UP5K EVN",
    "family": "iCE40",
    "fpga": "ICE40-UP5K",
    "pins": 11,
    "clock": "12 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "5,280 LUT4",
    "mem": "120 Kb BRAM + 1 Mb SPRAM",
    "best": "Official iCE40 UltraPlus evaluation board."
  },
  {
    "name": "Lattice Versa ECP5",
    "family": "ECP5",
    "fpga": "LFE5UM5G-45F",
    "pins": 16,
    "clock": "100 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "43,848 LUT4",
    "mem": "1,944 Kb BRAM",
    "best": "Lattice ECP5 reference and peripheral evaluation."
  },
  {
    "name": "LimeSDR Mini V2",
    "family": "ECP5",
    "fpga": "LFE5U",
    "pins": 14,
    "clock": "40 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "",
    "mem": "",
    "best": "Software-defined radio front-ends."
  },
  {
    "name": "LiteX Acorn Baseboard",
    "family": "ECP5",
    "fpga": "LFE5UM5G-45F",
    "pins": 23,
    "clock": "50 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "43,848 LUT4",
    "mem": "1,944 Kb BRAM",
    "best": "LiteX SoCs on Acorn accelerator cards."
  },
  {
    "name": "OrangeCrab r0.2 25F",
    "family": "ECP5",
    "fpga": "LFE5U-25F",
    "pins": 81,
    "clock": "48 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "24,288 LUT4",
    "mem": "1,008 Kb BRAM",
    "best": "Feather-form ECP5 work with DDR3 and native USB."
  },
  {
    "name": "RCS Arctic Tern BMC Card",
    "family": "ECP5",
    "fpga": "LFE5UM5G",
    "pins": 8,
    "clock": "125 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "",
    "mem": "",
    "best": "Open-source ECP5 development on the full Yosys + nextpnr flow."
  },
  {
    "name": "TrellisBoard",
    "family": "ECP5",
    "fpga": "LFE5UM5G-85F",
    "pins": 9,
    "clock": "12 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "83,640 LUT4",
    "mem": "3,744 Kb BRAM",
    "best": "Large open-source ECP5 reference designs."
  },
  {
    "name": "ULX3S",
    "family": "ECP5",
    "fpga": "LFE5U-12F",
    "pins": 15,
    "clock": "25 MHz",
    "toolchain": "Yosys + NextPNR",
    "support": "full",
    "luts": "12,144 LUT4",
    "mem": "304 Kb BRAM",
    "best": "Retro computing, HDMI video, and open-source SoCs."
  }
];
window.ALLORA_BOARDS_PINS = [
  {
    "name": "Arty A7",
    "family": "Xilinx",
    "fpga": "XC7A35T",
    "pins": 24,
    "clock": "100 MHz",
    "toolchain": "Vivado",
    "support": "pins"
  },
  {
    "name": "Digilent BASYS3",
    "family": "Xilinx",
    "fpga": "XC7A35T",
    "pins": 43,
    "clock": "100 MHz",
    "toolchain": "Vivado",
    "support": "pins"
  },
  {
    "name": "Digilent Nexys 4 DDR",
    "family": "Xilinx",
    "fpga": "XC7A100TCSG324",
    "pins": 48,
    "clock": "100 MHz",
    "toolchain": "Vivado",
    "support": "pins"
  },
  {
    "name": "Digilent GENESYS2",
    "family": "Xilinx",
    "fpga": "XC7K325T",
    "pins": 19,
    "clock": "200 MHz",
    "toolchain": "Vivado",
    "support": "pins"
  },
  {
    "name": "Digilent Zedboard",
    "family": "Xilinx",
    "fpga": "XC7Z020CLG484",
    "pins": 18,
    "clock": "100 MHz",
    "toolchain": "Vivado",
    "support": "pins"
  },
  {
    "name": "Digilent PYNQ-Z1",
    "family": "Xilinx",
    "fpga": "XC7Z020",
    "pins": 31,
    "clock": "125 MHz",
    "toolchain": "Vivado",
    "support": "pins"
  },
  {
    "name": "Digilent Zybo Z7",
    "family": "Other",
    "fpga": "UNKNOWN",
    "pins": 8,
    "clock": "125 MHz",
    "toolchain": "Vivado",
    "support": "pins"
  },
  {
    "name": "Digilent Cmod A7",
    "family": "Other",
    "fpga": "UNKNOWN",
    "pins": 11,
    "clock": "12 MHz",
    "toolchain": "Vivado",
    "support": "pins"
  },
  {
    "name": "Digilent Arty S7",
    "family": "Other",
    "fpga": "UNKNOWN",
    "pins": 22,
    "clock": "100 MHz",
    "toolchain": "Vivado",
    "support": "pins"
  },
  {
    "name": "Alchitry Au",
    "family": "Other",
    "fpga": "UNKNOWN",
    "pins": 16,
    "clock": "100 MHz",
    "toolchain": "Vivado",
    "support": "pins"
  },
  {
    "name": "Cologne Chip GateMate EVB",
    "family": "GateMate",
    "fpga": "CCGM1A1",
    "pins": 13,
    "clock": "10 MHz",
    "toolchain": "gatemate",
    "support": "pins"
  },
  {
    "name": "Tang Nano",
    "family": "Gowin",
    "fpga": "GW1NR-9C",
    "pins": 19,
    "clock": "27 MHz",
    "toolchain": "gowin",
    "support": "pins"
  },
  {
    "name": "Efinix Xyloni Dev Kit",
    "family": "Efinix",
    "fpga": "T8F81C2",
    "pins": 4,
    "clock": "33 MHz",
    "toolchain": "efinity",
    "support": "pins"
  },
  {
    "name": "Lattice Crosslink Nx Evn",
    "family": "Lattice Nexus",
    "fpga": "LIFCL-40-9BG400C",
    "pins": 13,
    "clock": "12 MHz",
    "toolchain": "radiant",
    "support": "pins"
  }
];
window.ALLORA_PINS_TOTAL = 202;
