// Generated by Allora Register Builder V1. Regenerate in the builder.
// Byte addresses; synchronous reset/writes, combinational reads. Hardware set wins W1C clear.
module demo_registers (
  input wire clk,
  input wire rst,
  input wire [7:0] addr,
  input wire [31:0] wr_data,
  output wire [31:0] rd_data,
  input wire wr_en,
  input wire rd_en,
  output wire [7:0] reg_CONTROL_value_o,
  output wire reg_CONTROL_write_o,
  output wire field_CONTROL_ENABLE_value_o,
  output wire [7:0] reg_STATUS_value_o,
  output wire reg_STATUS_write_o,
  input wire [7:0] field_STATUS_COUNT_i,
  output wire [7:0] reg_COMMAND_value_o,
  output wire reg_COMMAND_write_o,
  output wire [7:0] reg_FLAGS_value_o,
  output wire reg_FLAGS_write_o,
  input wire [7:0] reg_FLAGS_set_i
);

  // CONTROL @ 0x00: Counter control
  assign reg_CONTROL_write_o = wr_en && !rst && (addr == 8'h00);
  reg field_CONTROL_ENABLE_q;
  always @(posedge clk) begin
    if (rst) field_CONTROL_ENABLE_q <= 1'h0;
    else if (reg_CONTROL_write_o) field_CONTROL_ENABLE_q <= wr_data[0:0];
  end
  assign field_CONTROL_ENABLE_value_o = field_CONTROL_ENABLE_q;
  assign reg_CONTROL_value_o[0:0] = field_CONTROL_ENABLE_q;
  reg [6:0] gap_CONTROL_1_7_q;
  always @(posedge clk) begin
    if (rst) gap_CONTROL_1_7_q <= 7'h00;
    else if (reg_CONTROL_write_o) gap_CONTROL_1_7_q <= wr_data[7:1];
  end
  assign reg_CONTROL_value_o[7:1] = gap_CONTROL_1_7_q;

  // STATUS @ 0x04: Hardware counter value
  assign reg_STATUS_write_o = 1'b0;
  assign reg_STATUS_value_o[7:0] = field_STATUS_COUNT_i;

  // COMMAND @ 0x08: Write-only command value
  assign reg_COMMAND_write_o = wr_en && !rst && (addr == 8'h08);
  reg [7:0] reg_COMMAND_q;
  always @(posedge clk) begin
    if (rst) reg_COMMAND_q <= 8'h00;
    else if (reg_COMMAND_write_o) reg_COMMAND_q <= wr_data[7:0];
  end
  assign reg_COMMAND_value_o[7:0] = reg_COMMAND_q;

  // FLAGS @ 0x0c: Sticky flags; hardware set wins simultaneous clear
  assign reg_FLAGS_write_o = wr_en && !rst && (addr == 8'h0c);
  reg [7:0] reg_FLAGS_q;
  always @(posedge clk) begin
    if (rst) reg_FLAGS_q <= 8'h03;
    else reg_FLAGS_q <= (reg_FLAGS_q & ~(reg_FLAGS_write_o ? wr_data[7:0] : 8'h00)) | reg_FLAGS_set_i;
  end
  assign reg_FLAGS_value_o[7:0] = reg_FLAGS_q;

  reg [31:0] read_value;
  assign rd_data = read_value;
  always @* begin
    read_value = 32'h00000000;
    if (rd_en) begin
      case (addr)
        8'h00: begin
          read_value[0:0] = reg_CONTROL_value_o[0:0];
          read_value[7:1] = reg_CONTROL_value_o[7:1];
        end
        8'h04: begin
          read_value[7:0] = reg_STATUS_value_o[7:0];
        end
        8'h08: begin
        end
        8'h0c: begin
          read_value[7:0] = reg_FLAGS_value_o[7:0];
        end
        default: ;
      endcase
    end
  end
endmodule
